### ISSUE TITLE
Changing plugin using in pom.xml

### ISSUE THREAD

**Issue by silverskyvicto** [Alfresco/alfresco-helloworld-transformer#5]
Hi.

According to page below, `fabric8-maven-plugin` project has been moved to `Jkube`.

Reference: [README.md - fabric8-maven-plugin](https://github.com/fabric8io/fabric8-maven-plugin#fabric8-maven-plugin)

How about changing `fabric8-maven-plugin` to `kubernetes-maven-plugin`?

Thank you.

**Comment by mteodori** [comment]
Use docker-maven-plugin
